### ISSUE TITLE
SSL configuration for wss client

### ISSUE THREAD

**Issue by vp00** [ithewei/libhv#74]
Hi. Is there any guide or documentation on how to configure ssl certificate pinning for a WebSocketClient instance? I have already checked its header and I can't find any extensive configuration options. It seems right now it just accepts any self signed certificate, which would allow for man-in-the-middle attacks. 

I have seen some libraries utilizing a callback for the user to verify the certificate. I was thinking this would be useful, I can just compare the public key myself. Do you have something similar?

**Comment by vp00** [comment]
I see it calls `withTLS()` if the protocol is wss, which seems to accept a path to a certificate. I am pursuing the option of making my own WebSocketClient. Slight problem, this requires me to save the certificate on disk allowing it to be tampered with :(

**Comment by ithewei** [comment]
In order to simplify use, libhv uses a global SSL_CTX, which can be initialized with hssl_ctx_init. The interface to enable SSL is hio_enable_ssl(), and the C++ interface is withTLS(). If you want to verify peer certificate, please set hssl_ctx_init_param_t.verify_peer=1. You can refer to this  [examples/websocket_server_test.cpp](https://github.com/ithewei/libhv/blob/master/examples/websocket_server_test.cpp)

**Comment by vp00** [comment]
This was helpful and will allow me to do what I want. 

Thank you for your quick reply.
